apiVersion: devops.alauda.io/v1alpha1
kind: ClusterPipelineTemplate
metadata:
  annotations:
    displayName.en: Template of chart generate
    displayName.zh-CN: Chart OCI制品生成
    style.icon: "0.1"
    version: "0.45"
  labels:
    category: chart
  name: chart-generate
spec:
  engine: graph
  withSCM: true
  stages:
    - display: {}
      name: clone
      tasks:
        - display: {}
          id: clone
          kind: ClusterPipelineTaskTemplate
          name: clone
          type: ""
    - display: {}
      name: chart
      tasks:
        - display: {}
          id: chart-generate
          kind: ClusterPipelineTaskTemplate
          name: chart-update
          type: ""
  parameters:
    - name: overRideImages
      type: StringParameterDefinition
      value: ""
      description: override image info. for example devopsX=v3.3.1,devopsApi=v3.3.1
    - name: overRideCharts
      type: StringParameterDefinition
      value: ""
      description: override chart info. for example baseInit=v3.4.0,sentry=v3.4.0  It is very useful for chart-base-operator
    - name: branchName
      type: StringParameterDefinition
      value: ""
      description: override branch in this pipeline config
  agent:
    label: base
  arguments:
    - displayName:
        en: Git Clone
        zh-CN: Git Clone
      items:
        - binding:
            - clone.args.PlatformCodeRepository
            - chart-generate.args.CodeRepo
          default: ""
          display:
            description:
              en: Select a code repository for the project.
              zh-CN: 请选择或输入要检出的代码仓库
            name:
              en: RepositoryPath
              zh-CN: 代码仓库
            type: alauda.io/coderepositorymix
          name: PlatformCodeRepository
          required: true
          schema:
            type: alauda.io/coderepositorymix
          value: ""
        - binding:
            - clone.args.Branch
          default: ""
          display:
            description:
              en: The code repository branch that you want to check out. The default value is master when it's a git repository. The default value is empty when it's svn repository
              zh-CN: 请选择要检出的代码仓库的分支，当仓库为Git时，不选择时则为master分支；当仓库为SVN时，不选择时则为空
            name:
              en: Branch
              zh-CN: 分支
            related: PlatformCodeRepository
            type: alauda.io/codebranch
          name: Branch
          required: false
          schema:
            type: string
          value: ""
        - binding:
            - clone.args.RelativeDirectory
          default: .
          display:
            description:
              en: Specify a local directory (relative to the workspace root) where the Git repository will be checked out. If left empty, the workspace root itself will be used
              zh-CN: 指定签出 Git 仓库的本地目录(相对于 workspace 根目录)。若为空，将使用 workspace 根目录
            name:
              en: RelativeDirectory
              zh-CN: 相对目录
            type: string
          name: RelativeDirectory
          required: false
          schema:
            type: string
          value: ""
    - displayName:
        en: Update Chart
        zh-CN: 更新Chart
      items:
        - binding:
            - chart-generate.args.ChartDirectory
          default: .
          display:
            description:
              en: Specify a folder where the chart's files are stored
              zh-CN: 请输入Chart所在文件的目录
            name:
              en: Chart Directory
              zh-CN: Chart目录
            type: string
          name: ChartDirectory
          required: true
          schema:
            type: string
          value: ""
        - binding:
            - chart-generate.args.HarborProject
          default: ""
          display:
            description:
              en: Harbor Project
              zh-CN: Harbor Project
            name:
              en: Harbor Project
              zh-CN: Harbor Project
            type: string
          name: HarborProject
          required: true
          schema:
            type: string
          value: ""
        - binding:
            - chart-generate.args.retry
          default: "3"
          display:
            description:
              zh-CN: 生成 chart 时的失败重试次数
            name:
              en: Retry Times
              zh-CN: 重试次数
            type: string
          name: retry
          required: false
          schema:
            type: string
          value: ""
        - name: "enableCommit"
          binding:
            - chart-generate.args.enableCommit
          schema:
            type: boolean
          display:
            type: boolean
            name:
              zh-CN: "是否Commit"
              en: "commit to repo"
            description:
              zh-CN: "是否将修改提交到代码仓库，且只对 master 和 release 分支生效，其他分支不生效"
              en: "Whether commit change to git repo, only work for master and release"
          required: false
          default: "false"
        - name: "MultipleCharts"
          schema:
            type: boolean
          required: false
          default: "false"
          binding:
            - "chart-generate.args.MultipleCharts"
          display:
            type: boolean
            name:
              zh-CN: "此代码仓库维护多个chart"
              en: "Code repository has multiple charts"
            description:
              zh-CN: "此代码仓库维护多个chart，所以需要单独维护不同的chart的版本"
              en: "Code repository has multiple charts, and needs to have different sequential numbers"
  supportedTriggers:
    - type: codeTrigger
    - type: cron